/**
 * Guard for the document `<title>`, which is the one string that reaches a
 * browser tab, a bookmark and a search result before anyone has read a word of
 * the page.
 *
 * Every `metaTitle` key in the catalogs names the PAGE and only the page, so
 * before `documentTitle` existed the whole app served titles like `Lists` and
 * `Übersetzen` with the product name nowhere in the document. That is not a
 * typecheck failure and not a render failure, so nothing caught it: the page
 * was correct, it was just anonymous.
 *
 * The split between the two helpers is the part worth pinning. `documentTitle`
 * carries the brand, `metaTitle` must not, because `metaTitle` also renders
 * `<meta name="description">` and a description ending in a product name reads
 * as spam. A future edit that "simplifies" the two into one breaks one of the
 * two surfaces, and only this test says which.
 *
 * Wording is deliberately NOT asserted here. The catalogs are generated by the
 * workspace `wordsmith` CLI, so a test pinned to a German page name would read
 * a legitimate re-run as a regression, exactly as `i18n-locales.test.ts`
 * explains. These cases assert the SHAPE the helper imposes on whatever wording
 * it is handed.
 */
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';

import { APP_NAME } from '../../app/lib/app-name';
import { documentTitle, metaTitle } from '../../app/i18n/meta-title';

describe('documentTitle', () => {
  it('puts the product name after the page name', () => {
    const pageName = metaTitle('en', 'lists.metaTitle');
    assert.equal(documentTitle('en', 'lists.metaTitle'), `${pageName} · ${APP_NAME}`);
  });

  it('leads with the page name, because a tab truncates from the right', () => {
    // Two tabs are told apart by the half that survives truncation, so the
    // page name has to be the half that comes first.
    const title = documentTitle('en', 'history.metaTitle');
    assert.ok(
      title.indexOf(metaTitle('en', 'history.metaTitle')) < title.indexOf(APP_NAME),
      `page name should precede the product name, got: ${title}`,
    );
  });

  it('does not translate the product name', () => {
    // APP_NAME is a proper noun. A German title still ends in the same word.
    assert.ok(
      documentTitle('de', 'lists.metaTitle').endsWith(`· ${APP_NAME}`),
      `German title should end in the untranslated product name, got: ${documentTitle('de', 'lists.metaTitle')}`,
    );
  });

  it('still translates the page name itself', () => {
    // Otherwise the suffix could be hiding a title that stopped translating.
    assert.notEqual(metaTitle('de', 'lists.metaTitle'), metaTitle('en', 'lists.metaTitle'));
    assert.notEqual(documentTitle('de', 'lists.metaTitle'), documentTitle('en', 'lists.metaTitle'));
  });

  it('carries the brand across namespaces, not just `common`', () => {
    // The legal pages resolve through the `legal:` namespace and are the most
    // likely to be linked from outside, so they need the brand most.
    assert.ok(documentTitle('en', 'legal:meta.imprintTitle').endsWith(`· ${APP_NAME}`));
  });
});

describe('metaTitle', () => {
  it('leaves the product name off, so a description does not end in it', () => {
    const description = metaTitle('en', 'search.metaDescription');
    assert.ok(
      !description.includes(APP_NAME),
      `a description must not carry the brand suffix, got: ${description}`,
    );
  });

  it('is what documentTitle is built from, minus the suffix', () => {
    assert.equal(
      documentTitle('en', 'settings.metaTitle').replace(` · ${APP_NAME}`, ''),
      metaTitle('en', 'settings.metaTitle'),
    );
  });
});
